server:
  port: 8989

spring:
  datasource:
    url: jdbc:mysql://106.52.132.89:3306/fkwzxy?useSSL=false&serverTimezone=GMT
    password: wzh.000.
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
