server:
  port: 8989

spring:
  datasource:
    url: jdbc:mysql:///fkwzxy?useSSL=false&serverTimezone=GMT
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
